[pytest]

addopts =
    -v
    --tb=short
    --html=reports/report.html
    --self-contained-html

testpaths =
    tests

markers =
    smoke: Smoke tests
    regression: Regression tests
    sanity: Sanity tests