"""
What is Allure Report?

Allure Report is an advanced test reporting framework that generates interactive and visually rich reports for automated test execution.
If asked "Why Allure instead of HTML reports?"

Answer:

"Allure provides rich, interactive reports with execution steps, screenshots, logs, environment details, and attachments, making it much easier to debug failures compared to basic HTML reports.


Run PyTest
       │
       ▼
Generate Raw Results
(allure-results)
       │
       ▼
Generate HTML Report
(allure-report)
       │
       ▼
Open Report
Interview Questions
1. What is Allure Report?

Allure is a reporting framework that generates interactive reports with execution details, test steps, screenshots, attachments, and statistics.

2. Why is Allure preferred over HTML reports?

Because it provides richer debugging information, better visualization, attachments, and integrates well with CI/CD pipelines.

3. What is the purpose of --alluredir?

It tells PyTest where to store the raw Allure result files.

Example:

pytest --alluredir=allure-results
4. What is the difference between allure-results and allure-report?
allure-results/ → Raw JSON execution data generated by the PyTest plugin.
allure-report/ → Final HTML report generated from those results.
5. Which command opens the report?
allure open allure-report

Or:

allure serve allure-results
"""
import pytest

def test_addition():
    assert 2 + 2 == 4

def test_subtraction():
    assert 10 - 5 == 5

def test_failure():
    assert 5 == 10
